-- Human Resources Module Schema
-- Payroll management, wage tracking, and Vend payment integration

CREATE TABLE IF NOT EXISTS `payroll_runs` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `run_number` VARCHAR(50) NOT NULL UNIQUE,
    `pay_period_start` DATE NOT NULL,
    `pay_period_end` DATE NOT NULL,
    `pay_date` DATE NOT NULL,
    `status` ENUM('draft', 'calculated', 'approved', 'processed', 'completed', 'cancelled') DEFAULT 'draft',
    `total_gross_wages` DECIMAL(12,2) DEFAULT 0.00,
    `total_deductions` DECIMAL(12,2) DEFAULT 0.00,
    `total_net_wages` DECIMAL(12,2) DEFAULT 0.00,
    `total_tax` DECIMAL(12,2) DEFAULT 0.00,
    `total_kiwisaver` DECIMAL(12,2) DEFAULT 0.00,
    `total_employees` INT DEFAULT 0,
    `calculation_method` VARCHAR(100) COMMENT 'Deputy, manual, hybrid',
    `deputy_export_id` VARCHAR(100),
    `xero_batch_id` VARCHAR(100),
    `notes` TEXT,
    `calculated_at` TIMESTAMP NULL,
    `calculated_by` INT UNSIGNED,
    `approved_at` TIMESTAMP NULL,
    `approved_by` INT UNSIGNED,
    `processed_at` TIMESTAMP NULL,
    `processed_by` INT UNSIGNED,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_run_number (`run_number`),
    INDEX idx_period (`pay_period_start`, `pay_period_end`),
    INDEX idx_status (`status`),
    INDEX idx_pay_date (`pay_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payroll_timesheet_amendments` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `payroll_run_id` INT UNSIGNED NOT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `amendment_type` ENUM('missing_hours', 'incorrect_rate', 'unpaid_break', 'overtime_correction', 'public_holiday', 'other') NOT NULL,
    `original_hours` DECIMAL(5,2),
    `amended_hours` DECIMAL(5,2),
    `hours_difference` DECIMAL(5,2),
    `original_rate` DECIMAL(8,2),
    `amended_rate` DECIMAL(8,2),
    `amount_difference` DECIMAL(10,2) NOT NULL,
    `reason` TEXT NOT NULL,
    `shift_date` DATE,
    `deputy_timesheet_id` VARCHAR(100),
    `amendment_notes` TEXT,
    `requested_by` INT UNSIGNED NOT NULL,
    `approved_by` INT UNSIGNED,
    `approved_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`payroll_run_id`) REFERENCES `payroll_runs`(`id`) ON DELETE CASCADE,
    INDEX idx_payroll_run (`payroll_run_id`),
    INDEX idx_employee (`employee_id`),
    INDEX idx_type (`amendment_type`),
    INDEX idx_shift_date (`shift_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payroll_wage_discrepancies` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `payroll_run_id` INT UNSIGNED NOT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `discrepancy_type` ENUM('vend_mismatch', 'timesheet_gap', 'rate_error', 'calculation_error', 'missing_deduction', 'other') NOT NULL,
    `severity` ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
    `expected_amount` DECIMAL(10,2),
    `actual_amount` DECIMAL(10,2),
    `variance` DECIMAL(10,2),
    `description` TEXT NOT NULL,
    `vend_data` JSON COMMENT 'Related Vend payment data',
    `deputy_data` JSON COMMENT 'Related Deputy timesheet data',
    `status` ENUM('identified', 'investigating', 'resolved', 'ignored') DEFAULT 'identified',
    `resolution_notes` TEXT,
    `identified_by` INT UNSIGNED,
    `resolved_by` INT UNSIGNED,
    `identified_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `resolved_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`payroll_run_id`) REFERENCES `payroll_runs`(`id`) ON DELETE CASCADE,
    INDEX idx_payroll_run (`payroll_run_id`),
    INDEX idx_employee (`employee_id`),
    INDEX idx_type (`discrepancy_type`),
    INDEX idx_severity (`severity`),
    INDEX idx_status (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payroll_employee_details` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT UNSIGNED NOT NULL UNIQUE,
    `ird_number` VARCHAR(20),
    `tax_code` VARCHAR(10),
    `kiwisaver_rate` DECIMAL(4,2) COMMENT 'Percentage',
    `kiwisaver_status` ENUM('not_enrolled', 'enrolled', 'savings_suspension', 'opt_out') DEFAULT 'not_enrolled',
    `student_loan` TINYINT(1) DEFAULT 0,
    `child_support` TINYINT(1) DEFAULT 0,
    `child_support_amount` DECIMAL(10,2),
    `extra_pay_deductions` JSON COMMENT 'Additional deductions',
    `bank_account_name` VARCHAR(255),
    `bank_account_number` VARCHAR(50),
    `default_hourly_rate` DECIMAL(8,2),
    `salary_amount` DECIMAL(12,2) COMMENT 'For salaried employees',
    `employment_type` ENUM('full_time', 'part_time', 'casual', 'contractor') NOT NULL,
    `payment_frequency` ENUM('weekly', 'fortnightly', 'monthly') DEFAULT 'fortnightly',
    `xero_employee_id` VARCHAR(100),
    `deputy_employee_id` VARCHAR(100),
    `notes` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_employee (`employee_id`),
    INDEX idx_xero (`xero_employee_id`),
    INDEX idx_deputy (`deputy_employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payroll_vend_payment_requests` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT UNSIGNED NOT NULL,
    `vend_register_id` VARCHAR(36),
    `outlet_id` INT UNSIGNED,
    `request_date` DATE NOT NULL,
    `shift_start` DATETIME,
    `shift_end` DATETIME,
    `hours_worked` DECIMAL(5,2),
    `hourly_rate` DECIMAL(8,2),
    `amount_requested` DECIMAL(10,2) NOT NULL,
    `payment_reason` ENUM('wages', 'advance', 'reimbursement', 'bonus', 'other') NOT NULL,
    `status` ENUM('pending', 'approved', 'paid', 'rejected', 'cancelled') DEFAULT 'pending',
    `vend_payment_id` VARCHAR(36) COMMENT 'Vend payment record ID',
    `payroll_run_id` INT UNSIGNED COMMENT 'Linked to payroll run if processed',
    `approved_by` INT UNSIGNED,
    `approved_at` TIMESTAMP NULL,
    `paid_at` TIMESTAMP NULL,
    `rejection_reason` TEXT,
    `notes` TEXT,
    `metadata` JSON COMMENT 'Additional context from Vend',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`payroll_run_id`) REFERENCES `payroll_runs`(`id`) ON DELETE SET NULL,
    INDEX idx_employee (`employee_id`),
    INDEX idx_status (`status`),
    INDEX idx_request_date (`request_date`),
    INDEX idx_payroll_run (`payroll_run_id`),
    INDEX idx_vend_payment (`vend_payment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payroll_audit_log` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `payroll_run_id` INT UNSIGNED,
    `employee_id` INT UNSIGNED,
    `action` VARCHAR(100) NOT NULL,
    `action_type` ENUM('create', 'update', 'delete', 'approve', 'calculate', 'process') NOT NULL,
    `old_values` JSON,
    `new_values` JSON,
    `changes_summary` TEXT,
    `performed_by` INT UNSIGNED NOT NULL,
    `ip_address` VARCHAR(45),
    `user_agent` VARCHAR(500),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_payroll_run (`payroll_run_id`),
    INDEX idx_employee (`employee_id`),
    INDEX idx_action_type (`action_type`),
    INDEX idx_created (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
