-- E-Commerce Operations Module Schema
-- Multi-site e-commerce management and synchronization

CREATE TABLE IF NOT EXISTS `ecom_orders` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `order_number` VARCHAR(50) NOT NULL UNIQUE,
    `site_id` VARCHAR(50) NOT NULL COMMENT 'vapeshed, vapingkiwi, vapehq',
    `vend_sale_id` VARCHAR(36) COMMENT 'Linked Vend sale ID',
    `customer_id` INT UNSIGNED,
    `customer_email` VARCHAR(255) NOT NULL,
    `customer_name` VARCHAR(255) NOT NULL,
    `customer_phone` VARCHAR(50),
    `order_status` ENUM('pending', 'processing', 'awaiting_verification', 'verified', 'packed', 'shipped', 'delivered', 'cancelled', 'refunded') DEFAULT 'pending',
    `payment_status` ENUM('pending', 'paid', 'failed', 'refunded', 'partial_refund') DEFAULT 'pending',
    `payment_method` VARCHAR(50),
    `payment_reference` VARCHAR(100),
    `subtotal` DECIMAL(10,2) NOT NULL,
    `shipping_cost` DECIMAL(10,2) DEFAULT 0.00,
    `tax_amount` DECIMAL(10,2) DEFAULT 0.00,
    `discount_amount` DECIMAL(10,2) DEFAULT 0.00,
    `total_amount` DECIMAL(10,2) NOT NULL,
    `shipping_address_line1` VARCHAR(255),
    `shipping_address_line2` VARCHAR(255),
    `shipping_city` VARCHAR(100),
    `shipping_region` VARCHAR(100),
    `shipping_postcode` VARCHAR(20),
    `shipping_country` VARCHAR(50) DEFAULT 'New Zealand',
    `billing_address_same` TINYINT(1) DEFAULT 1,
    `billing_address_line1` VARCHAR(255),
    `billing_address_line2` VARCHAR(255),
    `billing_city` VARCHAR(100),
    `billing_region` VARCHAR(100),
    `billing_postcode` VARCHAR(20),
    `billing_country` VARCHAR(50) DEFAULT 'New Zealand',
    `age_verified` TINYINT(1) DEFAULT 0,
    `age_verification_method` VARCHAR(50),
    `age_verified_at` TIMESTAMP NULL,
    `tracking_number` VARCHAR(100),
    `courier` VARCHAR(50),
    `notes` TEXT,
    `admin_notes` TEXT,
    `ip_address` VARCHAR(45),
    `user_agent` VARCHAR(500),
    `order_placed_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `processed_at` TIMESTAMP NULL,
    `shipped_at` TIMESTAMP NULL,
    `delivered_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_order_number (`order_number`),
    INDEX idx_site (`site_id`),
    INDEX idx_customer (`customer_id`),
    INDEX idx_email (`customer_email`),
    INDEX idx_status (`order_status`),
    INDEX idx_payment (`payment_status`),
    INDEX idx_vend (`vend_sale_id`),
    INDEX idx_placed (`order_placed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ecom_order_items` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `order_id` BIGINT UNSIGNED NOT NULL,
    `product_id` INT UNSIGNED NOT NULL,
    `vend_product_id` VARCHAR(36),
    `sku` VARCHAR(100) NOT NULL,
    `product_name` VARCHAR(255) NOT NULL,
    `quantity` INT NOT NULL,
    `unit_price` DECIMAL(10,2) NOT NULL,
    `discount_amount` DECIMAL(10,2) DEFAULT 0.00,
    `tax_amount` DECIMAL(10,2) DEFAULT 0.00,
    `total_price` DECIMAL(10,2) NOT NULL,
    `variant_id` INT UNSIGNED,
    `variant_details` JSON COMMENT 'Size, color, flavor, etc',
    `notes` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`order_id`) REFERENCES `ecom_orders`(`id`) ON DELETE CASCADE,
    INDEX idx_order (`order_id`),
    INDEX idx_product (`product_id`),
    INDEX idx_sku (`sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ecom_inventory_sync` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `product_id` INT UNSIGNED NOT NULL,
    `sku` VARCHAR(100) NOT NULL,
    `site_id` VARCHAR(50) NOT NULL,
    `vend_outlet_id` VARCHAR(36),
    `site_stock_level` INT NOT NULL,
    `vend_stock_level` INT,
    `sync_status` ENUM('synced', 'out_of_sync', 'error') DEFAULT 'synced',
    `variance` INT DEFAULT 0,
    `last_synced_at` TIMESTAMP NULL,
    `last_sync_error` TEXT,
    `sync_attempts` INT DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `unique_product_site` (`product_id`, `site_id`),
    INDEX idx_product (`product_id`),
    INDEX idx_sku (`sku`),
    INDEX idx_site (`site_id`),
    INDEX idx_status (`sync_status`),
    INDEX idx_synced (`last_synced_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ecom_age_verify` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `order_id` BIGINT UNSIGNED,
    `customer_id` INT UNSIGNED,
    `customer_email` VARCHAR(255) NOT NULL,
    `verification_token` VARCHAR(64) UNIQUE NOT NULL,
    `verification_method` ENUM('photo_id', 'postal_verification', 'realme', 'manual') NOT NULL,
    `status` ENUM('pending', 'approved', 'rejected', 'expired') DEFAULT 'pending',
    `id_photo_path` VARCHAR(500),
    `id_type` VARCHAR(50) COMMENT 'drivers_license, passport, etc',
    `date_of_birth` DATE,
    `verified_age` INT,
    `rejection_reason` TEXT,
    `reviewed_by` INT UNSIGNED,
    `reviewed_at` TIMESTAMP NULL,
    `submitted_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `expires_at` TIMESTAMP NULL,
    `ip_address` VARCHAR(45),
    `user_agent` VARCHAR(500),
    `metadata` JSON,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`order_id`) REFERENCES `ecom_orders`(`id`) ON DELETE SET NULL,
    INDEX idx_order (`order_id`),
    INDEX idx_customer (`customer_id`),
    INDEX idx_email (`customer_email`),
    INDEX idx_token (`verification_token`),
    INDEX idx_status (`status`),
    INDEX idx_submitted (`submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ecom_site_sync_log` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `site_id` VARCHAR(50) NOT NULL,
    `sync_type` ENUM('inventory', 'products', 'orders', 'customers', 'prices') NOT NULL,
    `sync_direction` ENUM('to_vend', 'from_vend', 'bidirectional') NOT NULL,
    `records_processed` INT DEFAULT 0,
    `records_synced` INT DEFAULT 0,
    `records_failed` INT DEFAULT 0,
    `sync_status` ENUM('success', 'partial', 'failed') NOT NULL,
    `error_log` JSON,
    `started_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `completed_at` TIMESTAMP NULL,
    `duration_seconds` INT,
    INDEX idx_site (`site_id`),
    INDEX idx_type (`sync_type`),
    INDEX idx_status (`sync_status`),
    INDEX idx_started (`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
