-- Staff Accounts Module Schema
-- Staff credit, payment plans, and financial reconciliation

CREATE TABLE IF NOT EXISTS `staff_account_reconciliation` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT UNSIGNED NOT NULL,
    `period_start` DATE NOT NULL,
    `period_end` DATE NOT NULL,
    `opening_balance` DECIMAL(10,2) DEFAULT 0.00,
    `total_purchases` DECIMAL(10,2) DEFAULT 0.00,
    `total_payments` DECIMAL(10,2) DEFAULT 0.00,
    `total_refunds` DECIMAL(10,2) DEFAULT 0.00,
    `total_adjustments` DECIMAL(10,2) DEFAULT 0.00,
    `closing_balance` DECIMAL(10,2) DEFAULT 0.00,
    `status` ENUM('pending', 'balanced', 'variance', 'under_review') DEFAULT 'pending',
    `variance_amount` DECIMAL(10,2) DEFAULT 0.00,
    `variance_notes` TEXT,
    `reconciled_by` INT UNSIGNED,
    `reconciled_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `unique_employee_period` (`employee_id`, `period_start`),
    INDEX idx_employee (`employee_id`),
    INDEX idx_period (`period_start`, `period_end`),
    INDEX idx_status (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `staff_payment_transactions` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT UNSIGNED NOT NULL,
    `transaction_type` ENUM('purchase', 'payment', 'refund', 'adjustment', 'transfer') NOT NULL,
    `amount` DECIMAL(10,2) NOT NULL,
    `payment_method` VARCHAR(50) COMMENT 'cash, eftpos, wage_deduction, card_on_file, etc',
    `payment_plan_id` INT UNSIGNED COMMENT 'If part of payment plan',
    `vend_sale_id` VARCHAR(36) COMMENT 'Related Vend sale',
    `outlet_id` INT UNSIGNED,
    `description` VARCHAR(500),
    `notes` TEXT,
    `processed_by` INT UNSIGNED,
    `processed_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `voided` TINYINT(1) DEFAULT 0,
    `voided_by` INT UNSIGNED,
    `voided_at` TIMESTAMP NULL,
    `void_reason` TEXT,
    `balance_after` DECIMAL(10,2) COMMENT 'Running balance after transaction',
    `metadata` JSON,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_employee (`employee_id`),
    INDEX idx_type (`transaction_type`),
    INDEX idx_payment_plan (`payment_plan_id`),
    INDEX idx_vend (`vend_sale_id`),
    INDEX idx_processed (`processed_at`),
    INDEX idx_voided (`voided`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `staff_saved_cards` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT UNSIGNED NOT NULL,
    `card_token` VARCHAR(255) NOT NULL COMMENT 'Encrypted/tokenized card details',
    `card_type` VARCHAR(50) COMMENT 'Visa, Mastercard, etc',
    `last_four` VARCHAR(4) NOT NULL,
    `expiry_month` INT NOT NULL,
    `expiry_year` INT NOT NULL,
    `cardholder_name` VARCHAR(255),
    `is_default` TINYINT(1) DEFAULT 0,
    `active` TINYINT(1) DEFAULT 1,
    `payment_gateway` VARCHAR(50) COMMENT 'Stripe, PaymentExpress, etc',
    `gateway_customer_id` VARCHAR(100),
    `added_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `last_used_at` TIMESTAMP NULL,
    `total_transactions` INT DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_employee (`employee_id`),
    INDEX idx_active (`active`),
    INDEX idx_default (`is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `staff_payment_plans` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT UNSIGNED NOT NULL,
    `plan_name` VARCHAR(100),
    `total_amount` DECIMAL(10,2) NOT NULL,
    `amount_paid` DECIMAL(10,2) DEFAULT 0.00,
    `remaining_balance` DECIMAL(10,2) NOT NULL,
    `installment_amount` DECIMAL(10,2) NOT NULL,
    `installment_frequency` ENUM('weekly', 'fortnightly', 'monthly') NOT NULL,
    `total_installments` INT NOT NULL,
    `installments_paid` INT DEFAULT 0,
    `start_date` DATE NOT NULL,
    `next_payment_date` DATE NOT NULL,
    `completion_date` DATE,
    `status` ENUM('active', 'completed', 'cancelled', 'defaulted') DEFAULT 'active',
    `auto_deduct_from_wages` TINYINT(1) DEFAULT 0,
    `saved_card_id` INT UNSIGNED,
    `notes` TEXT,
    `approved_by` INT UNSIGNED NOT NULL,
    `approved_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `completed_at` TIMESTAMP NULL,
    `cancelled_at` TIMESTAMP NULL,
    `cancellation_reason` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`saved_card_id`) REFERENCES `staff_saved_cards`(`id`) ON DELETE SET NULL,
    INDEX idx_employee (`employee_id`),
    INDEX idx_status (`status`),
    INDEX idx_next_payment (`next_payment_date`),
    INDEX idx_card (`saved_card_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `staff_payment_plan_installments` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `payment_plan_id` INT UNSIGNED NOT NULL,
    `installment_number` INT NOT NULL,
    `due_date` DATE NOT NULL,
    `amount_due` DECIMAL(10,2) NOT NULL,
    `amount_paid` DECIMAL(10,2) DEFAULT 0.00,
    `status` ENUM('pending', 'paid', 'overdue', 'skipped') DEFAULT 'pending',
    `payment_transaction_id` BIGINT UNSIGNED,
    `paid_at` TIMESTAMP NULL,
    `notes` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`payment_plan_id`) REFERENCES `staff_payment_plans`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`payment_transaction_id`) REFERENCES `staff_payment_transactions`(`id`) ON DELETE SET NULL,
    INDEX idx_plan (`payment_plan_id`),
    INDEX idx_due_date (`due_date`),
    INDEX idx_status (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `staff_reminder_log` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT UNSIGNED NOT NULL,
    `reminder_type` ENUM('balance_due', 'payment_plan_due', 'overdue_payment', 'plan_completion', 'balance_updated') NOT NULL,
    `payment_plan_id` INT UNSIGNED,
    `message` TEXT NOT NULL,
    `delivery_method` ENUM('email', 'sms', 'system_notification') NOT NULL,
    `recipient` VARCHAR(255),
    `sent_status` ENUM('pending', 'sent', 'failed') DEFAULT 'pending',
    `sent_at` TIMESTAMP NULL,
    `error_message` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_employee (`employee_id`),
    INDEX idx_type (`reminder_type`),
    INDEX idx_status (`sent_status`),
    INDEX idx_sent (`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `staff_allocations` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT UNSIGNED NOT NULL,
    `allocation_type` ENUM('monthly_credit', 'quarterly_bonus', 'one_time_credit', 'employee_discount') NOT NULL,
    `amount` DECIMAL(10,2) NOT NULL,
    `remaining_amount` DECIMAL(10,2) NOT NULL,
    `description` VARCHAR(500),
    `valid_from` DATE NOT NULL,
    `valid_until` DATE NOT NULL,
    `status` ENUM('active', 'expired', 'fully_used', 'cancelled') DEFAULT 'active',
    `notes` TEXT,
    `approved_by` INT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_employee (`employee_id`),
    INDEX idx_type (`allocation_type`),
    INDEX idx_status (`status`),
    INDEX idx_valid (`valid_from`, `valid_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
