<?php


// Load core CIS application for authentication
$included = false;
$appCandidates = [
    (isset($_SERVER['DOCUMENT_ROOT']) ? rtrim($_SERVER['DOCUMENT_ROOT'], '/') : '') . '/app.php',
    '/home/129337.cloudwaysapps.com/jcepnzzkmj/public_html/app.php',
    '/home/master/applications/jcepnzzkmj/public_html/app.php'
];

// Enhanced output buffering to capture bootstrap constant warnings
ob_start();
foreach ($appCandidates as $candidate) {
    if (!$candidate) continue;
    if (is_readable($candidate)) {
        try {
            require_once $candidate;
            $included = true;
            break;
        } catch (Throwable $e) {
            // try next candidate
        }
    }
}

// Capture and discard any unwanted output (constant warnings, etc.)
$unwantedOutput = ob_get_contents();
ob_clean();

// Authentication guard - return empty JS config for unauthenticated users
if (function_exists('isLoggedIn')) {
    if (!isLoggedIn()) {
        header('Content-Type: application/javascript; charset=utf-8');
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        header('Pragma: no-cache');
        echo '// Authentication required - please log in at staff.vapeshed.co.nz' . "\n";
        echo 'window.CIS_CONFIG = { auth_required: true, login_url: "https://staff.vapeshed.co.nz/login.php" };';
        exit;
    }
}

// Set proper content type for JavaScript FIRST (before any output)
header('Content-Type: application/javascript; charset=utf-8');

// Prevent caching to ensure fresh config
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

/**
 * Fetch configuration from backend.php using the same method as frontend.php
 * This ensures consistency and avoids direct database access issues
 */
function fetch_init_for_config(): array {
  $ch = curl_init();
  curl_setopt_array($ch, [
    CURLOPT_URL => 'backend.php?api=1',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POST => true,
    CURLOPT_HTTPHEADER => ['Content-Type: application/json'],
    CURLOPT_POSTFIELDS => json_encode(['action' => 'init'])
  ]);
  $resp = curl_exec($ch);
  $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
  curl_close($ch);
  
  if ($httpCode !== 200) {
    error_log("config.js.php: backend.php returned HTTP $httpCode");
    return [];
  }
  
  $j = json_decode($resp ?? '', true);
  if ($j && !empty($j['ok']) && !empty($j['data'])) {
    // Store CSRF in session for future requests
    $_SESSION['tt_csrf'] = $j['data']['csrf_token'] ?? ($_SESSION['tt_csrf'] ?? '');
    return $j['data'];
  }
  
  error_log("config.js.php: Failed to parse backend.php response");
  return [];
}

// Fetch configuration
$d = fetch_init_for_config();
$csrf         = $d['csrf_token'] ?? ($_SESSION['tt_csrf'] ?? '');
$syncEnabled  = (bool)($d['sync_enabled'] ?? true);
$outlet_map   = $d['outlet_map']   ?? [];
$supplier_map = $d['supplier_map'] ?? [];
$ls_base      = $d['ls_consignment_base'] ?? 'https://vapeshed.retail.lightspeed.app/consignment/';


// Now output JavaScript (after all PHP processing)
?>
/**
 * config.js.php - Dynamic JavaScript Configuration
 * 
 * This file is served as application/javascript and injects APP_CONFIG
 * Generated: <?= date('Y-m-d H:i:s') ?>

 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Configuration is dynamically generated from PHP via backend.php
 */

(function() {
  'use strict';
  
  // ✅ Inject configuration into global scope
  window.APP_CONFIG = {
    CSRF: <?= json_encode($csrf, JSON_UNESCAPED_UNICODE) ?>,
    LS_CONSIGNMENT_BASE: <?= json_encode($ls_base, JSON_UNESCAPED_UNICODE) ?>,
    OUTLET_MAP: <?= json_encode($outlet_map, JSON_UNESCAPED_UNICODE) ?>,
    SUPPLIER_MAP: <?= json_encode($supplier_map, JSON_UNESCAPED_UNICODE) ?>,
    SYNC_ENABLED: <?= $syncEnabled ? 'true' : 'false' ?>,
    GENERATED_AT: '<?= date('c') ?>'
  };
  
  console.log('✅ Configuration injected from config.js.php');
  
})();
